---
- name: Deploy, configure, and populate flask repo and virtualenv
  hosts: backend_servers
  become: true
  gather_facts: false
  tags:
    - application_servers
    - flasks
  roles:
    - application
