- name: Play to automate process
  hosts: all
  become: yes
  vars:
    satellite_activationkey: gpte-labs-rhel8
    satellite_org: prod
  tasks:

    - name: install katello-ca-consumer package
      yum:
        name: http://satellite.example.com/pub/katello-ca-consumer-latest.noarch.rpm
        disable_gpg_check: true
        state: present

    - name: register system and attach subs
      redhat_subscription:
        state: present
        activationkey: "{{ satellite_activationkey }}"
        org_id: "{{ satellite_org }}"
        auto_attach: true

    - name: Install firewalld
      yum:
        name: firewalld
        state: latest
